"""add dead_letter table

Revision ID: 0b6b4972c9e9
Revises: a7870d170672
Create Date: 2026-07-21 19:09:01.080676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6b4972c9e9'
down_revision: Union[str, None] = 'a7870d170672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_uid', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('download', 'convert', 'normalize', 'render', name='pipelinestage'), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('delivery_attempt', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_uid', 'stage', name='uq_dead_letter_model_stage')
    )
    op.create_index(op.f('ix_dead_letter_model_uid'), 'dead_letter', ['model_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_model_uid'), table_name='dead_letter')
    op.drop_table('dead_letter')
    # ### end Alembic commands ###

    # Autogenerate omits this and Postgres ENUMs outlive their table, so without
    # it a downgrade→upgrade cycle fails with "type already exists"
    # (server.md#migrations).
    op.execute("DROP TYPE IF EXISTS pipelinestage")
