"""add training_metric.val_accuracy

Nullable, like val_loss: validation runs once per epoch, so the steps in between
have no accuracy to record. Existing rows keep null — the runs that predate this
column never measured it, and back-filling a zero would read as "the model got
everything wrong" rather than "not measured".

Revision ID: 49eb36f64ac4
Revises: d5a1c8b3e6f2
Create Date: 2026-07-26 11:49:19.988219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49eb36f64ac4'
down_revision: Union[str, None] = 'd5a1c8b3e6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_metric', sa.Column('val_accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_metric', 'val_accuracy')
    # ### end Alembic commands ###
