"""initial schema

Revision ID: a7870d170672
Revises: 
Create Date: 2026-07-21 18:38:30.934234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7870d170672'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('invite',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('model',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('download_status', sa.Enum('pending', 'downloaded', 'failed', name='downloadstatus'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('raw_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_uid', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('converted', 'normalized', 'rendered', name='artifactstage'), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='artifactstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_uid'], ['model.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_uid', 'stage', name='uq_artifact_model_stage')
    )
    op.create_index(op.f('ix_artifact_model_uid'), 'artifact', ['model_uid'], unique=False)
    op.create_table('email_verification',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_verification_user_id'), 'email_verification', ['user_id'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_uid', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('weak', 'manual', name='labelsource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('annotator', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_uid'], ['model.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_model_uid'), 'label', ['model_uid'], unique=False)
    op.create_table('session',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_label_model_uid'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_email_verification_user_id'), table_name='email_verification')
    op.drop_table('email_verification')
    op.drop_index(op.f('ix_artifact_model_uid'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_table('model')
    op.drop_table('invite')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###

    # Not auto-generated, and required: Postgres ENUM types outlive the tables
    # that use them, so without this a downgrade followed by an upgrade fails
    # with "type ... already exists". Verified by round-tripping this revision.
    for enum_name in (
        "downloadstatus",
        "artifactstage",
        "artifactstatus",
        "labelsource",
        "userrole",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
