"""add model.deleted_at for soft delete

Revision ID: fb0e0e1af523
Revises: 0b6b4972c9e9
Create Date: 2026-07-22 16:50:54.784161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0e0e1af523'
down_revision: Union[str, None] = '0b6b4972c9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'deleted_at')
    # ### end Alembic commands ###
