#!/usr/bin/env bash
#
# Delete the ingested objects from the GCS buckets — the inverse of
# reconcile_from_storage (server.md#deploying-the-api-to-cloud-run). This is the
# irreversible half of a clean slate: the buckets are the ONLY copy of the
# ingested data (there is no DB backup behind them — the model/artifact rows are
# reconstructed FROM these objects), so wiping raw/ means re-running the whole M4
# ingestion (~32k Objaverse downloads + convert/normalize/render) to restore it.
#
# Dry-run by default — it prints per-prefix object counts and total bytes and
# deletes NOTHING unless you pass --apply.
#
#   scripts/wipe_buckets.sh                 # dry-run, both prefixes
#   scripts/wipe_buckets.sh --raw           # dry-run, raw/ only
#   scripts/wipe_buckets.sh --processed     # dry-run, processed/ only
#   scripts/wipe_buckets.sh --apply         # actually delete (gated on a typed phrase)
#
# --raw wipes the downloaded meshes (expensive to restore); --processed wipes the
# renders (cheap — a re-render, no re-download). Default is both. This does NOT
# touch the database; reset that separately with `scripts/adopt_schema.sh --fresh`.

set -euo pipefail

# Load ./.env (gitignored) so bucket/project overrides are picked up (see .env.example).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
[[ -f "$REPO_ROOT/.env" ]] && { set -a; . "$REPO_ROOT/.env"; set +a; }

# ── Config (override via env) ───────────────────────────────────────────────
PROJECT="${IMAGEGENIE_GCP_PROJECT:-imagegenie-pipeline}"
RAW_BUCKET="${IMAGEGENIE_RAW_BUCKET:-${PROJECT}-raw}"
PROCESSED_BUCKET="${IMAGEGENIE_PROCESSED_BUCKET:-${PROJECT}-processed}"

# ── Args ────────────────────────────────────────────────────────────────────
APPLY=0
WIPE_RAW=0
WIPE_PROCESSED=0
for arg in "$@"; do
  case "$arg" in
    --apply)     APPLY=1 ;;
    --raw)       WIPE_RAW=1 ;;
    --processed) WIPE_PROCESSED=1 ;;
    *) printf 'unknown argument: %s\n' "$arg" >&2; exit 2 ;;
  esac
done
# No prefix flag ⇒ both.
if [[ "$WIPE_RAW" -eq 0 && "$WIPE_PROCESSED" -eq 0 ]]; then
  WIPE_RAW=1
  WIPE_PROCESSED=1
fi

log()  { printf '\033[1;34m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

command -v gcloud >/dev/null || die "gcloud not found"

# ── Tally what would be deleted ─────────────────────────────────────────────
# `gcloud storage du -s` returns "<bytes> <path>"; an empty prefix prints nothing.
tally() {
  local prefix="$1" line
  line="$(gcloud storage du -s "$prefix" 2>/dev/null || true)"
  printf '%s' "${line%% *}"  # leading field = total bytes ("" if empty)
}

human() {
  local bytes="${1:-0}"
  [[ -z "$bytes" ]] && bytes=0
  awk -v value="$bytes" 'BEGIN {
    split("B KB MB GB TB PB", unit, " ");
    index_pos = 1;
    while (value >= 1024 && index_pos < 6) { value /= 1024; index_pos++ }
    printf (index_pos == 1 ? "%d %s" : "%.1f %s"), value, unit[index_pos]
  }'
}

declare -a TARGETS=()
[[ "$WIPE_RAW" -eq 1 ]]       && TARGETS+=("gs://${RAW_BUCKET}/raw/")
[[ "$WIPE_PROCESSED" -eq 1 ]] && TARGETS+=("gs://${PROCESSED_BUCKET}/processed/")

log "Tallying objects under $(printf '%s ' "${TARGETS[@]}")"
total_bytes=0
any_objects=0
for prefix in "${TARGETS[@]}"; do
  bytes="$(tally "$prefix")"
  [[ -z "$bytes" ]] && bytes=0
  [[ "$bytes" -gt 0 ]] && any_objects=1
  total_bytes=$((total_bytes + bytes))
  printf '  %-52s %s\n' "$prefix" "$(human "$bytes")"
done
printf '  %-52s %s\n' "TOTAL" "$(human "$total_bytes")"

if [[ "$any_objects" -eq 0 ]]; then
  warn "nothing to delete — the selected prefixes are already empty."
  exit 0
fi

# ── Dry-run stops here ──────────────────────────────────────────────────────
if [[ "$APPLY" -ne 1 ]]; then
  cat <<EOF

  Dry run — nothing was deleted. Re-run with --apply to delete the above.

  Restoring raw/ afterwards means re-running M4 ingestion (thousands of
  Objaverse downloads); processed/ can be regenerated by re-rendering.
EOF
  exit 0
fi

# ── Confirm the destructive step ────────────────────────────────────────────
cat <<EOF

  About to PERMANENTLY DELETE every object under:
$(printf '    %s\n' "${TARGETS[@]}")
  totalling $(human "$total_bytes"). There is no DB backup behind these — this
  is the only copy. Restoring raw/ means re-ingesting from scratch.

EOF
read -r -p "  Type 'delete all objects' to proceed: " reply
[[ "$reply" == "delete all objects" ]] || die "aborted"

# ── Delete ──────────────────────────────────────────────────────────────────
for prefix in "${TARGETS[@]}"; do
  log "Deleting ${prefix}**"
  gcloud storage rm --recursive "$prefix" 2>/dev/null || die "delete failed for $prefix"
done

log "Done. Reset the database to match with: scripts/adopt_schema.sh --fresh"
